image: Visual Studio 2019
 
configuration:
  - Release

install:
  - ps: dotnet tool restore

build_script:
  - ps: dotnet cake

after_build:
  - ps: dotnet cake --target=PublishApps

test_script:
  - ps: dotnet cake --target=Test

after_test:
  - ps: dotnet cake --target=PublishCoverage
  - ps: Get-ChildItem ./.build/Packages/*.nupkg | % { Push-AppveyorArtifact $_.FullName -DeploymentName NuGetPackages }
  - ps: Get-ChildItem ./.build/Installers/*.msi | % { Push-AppveyorArtifact $_.FullName -DeploymentName WindowsInstallers }
  - ps: Get-ChildItem ./.build/PublishedApps/*.zip | % { Push-AppveyorArtifact $_.FullName -DeploymentName Apps }
  - ps: Get-ChildItem ./.build/CoverageResults/Coverage.*.cobertura.xml | % { Push-AppveyorArtifact $_.FullName -DeploymentName CoverageReports }

notifications:
- provider: Email
  to:
  - james@thehowats.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
