image: Visual Studio 2019

before_build:
  - ps: nuget restore src

build:
  publish_nuget: true
  project: src/SubEtha.sln

after_build:
  - ps: dotnet publish src/Matrix/Howatworks.Matrix.Site

configuration:
  - Release

test_script:
  - ps: dotnet tool install -g dotnet-reportgenerator-globaltool
  - ps: dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
  - ps: dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - ps: reportgenerator "-reports:src/**/coverage.opencover.xml" "-targetdir:AnalysisResults" "-reporttypes:HTMLSummary;JSONSummary;Badges"

artifacts:
  - path: src/Thumb.Assistant/Howatworks.Thumb.Assistant.Installer/Artifacts/SubEthaThumbAssistant.msi
    name: Thumb Assistant Installer
    type: file
  - path: src/Thumb.Matrix/Howatworks.Thumb.Matrix.Installer/Artifacts/SubEthaThumbMatrix.msi
    name: Thumb Assistant Installer
    type: file
  - path: src/Matrix/Howatworks.Matrix.Site/Artifacts/Howatworks.Matrix.Site-*.zip
    name: Matrix Site
    type: zip
  - path: src/**/coverage.opencover.xml
    name: OpenCover Reports
    type: file
  - path: AnalysisResults/summary.htm
    name: ReportGenerator Report
    type: file
  - path: AnalysisResults/Summary.json
    name: ReportGenerator Report
    type: file

notifications:
- provider: Email
  to:
  - james@thehowats.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
