image: Visual Studio 2019
 
configuration:
  - Release

install:
  - ps: dotnet tool restore

build_script:
  - ps: dotnet dotnet-cake

after_build:
  - ps: dotnet dotnet-cake --target=PublishApps

test_script:
  - ps: dotnet dotnet-cake --target=Test

after_test:
  - ps: dotnet dotnet-cake --target=PublishCoverage

artifacts:
  - path: src/Thumb.Assistant/Howatworks.Thumb.Assistant.Installer/Artifacts/SubEthaThumbAssistant.msi
    name: Thumb Assistant Installer
    type: file
  - path: .build/PublishedApps/Howatworks.Thumb.Assistant.Console-*.zip
    name: Thumb Assistant Console
    type: file
  - path: src/Thumb.Matrix/Howatworks.Thumb.Matrix.Installer/Artifacts/SubEthaThumbMatrix.msi
    name: Thumb Matrix Installer
    type: file
  - path: .build/PublishedApps/Howatworks.Thumb.Matrix.Console-*.zip
    name: Thumb Matrix Console
    type: file
  - path: .build/PublishedApps/Howatworks.Matrix.Site-*.zip
    name: Matrix Site
    type: zip
  - path: .build/Packages/*.nupkg
    name: Packages
    type: file
  - path: .build/CoverageResults/Coverage.*.cobertura.xml
    name: Coverlet Reports
    type: file

notifications:
- provider: Email
  to:
  - james@thehowats.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
