image: Visual Studio 2017

before_build:
  - ps: nuget restore src

build:
  publish_nuget: true
  project: src/SubEtha.sln

after_build:
  - ps: dotnet publish src/Matrix/Howatworks.Matrix.Site
  
configuration:
  - Release

test_script:
  - ps: dotnet test src /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  
artifacts:
  - path: src/Thumb.Assistant/Howatworks.Thumb.Assistant.Installer/Artifacts/SubEthaThumbAssistant.msi
    name: Thumb Assistant Installer
    type: file
  - path: src/Thumb.Matrix/Howatworks.Thumb.Matrix.Installer/Artifacts/SubEthaMatrixAssistant.msi
    name: Thumb Assistant Installer
    type: file
  - path: src/Matrix/Howatworks.Matrix.Site/Artifacts/Howatworks.Matrix.Site-0.2.2-alpha0001.zip
    name: Matrix Site
    type: zip
  - path: src/**/coverage.opencover.xml
    name: OpenCover Reports
    type: file

notifications:
- provider: Email
  to:
  - james@thehowats.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true