image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: nuget restore src

build:
  publish_nuget: true
  project: src/SubEtha.sln

test_script:
  - ps: dotnet test src
