image: Visual Studio 2019
 
configuration:
  - Release

install:
  - pwsh: dotnet tool restore

build_script:
  - pwsh: dotnet dotnet-cake

after_build:
  - pwsh: dotnet dotnet-cake --target=PublishApps

test_script:
  - pwsh: dotnet dotnet-cake --target=Test

after_test:
  - pwsh: dotnet dotnet-cake --target=PublishCoverage
  - pwsh: Get-ChildItem ./.build/Packages/*.nupkg | % { Push-AppveyorArtifact $_.FullName -DeploymentName NuGetPackages }
  - pwsh: Get-ChildItem -Recurse ./src/*/Artifacts/*.msi | % { Push-AppveyorArtifact $_.FullName -DeploymentName WindowsInstallers }
  - pwsh: Get-ChildItem -Recurse ./.build/PublishedApps/*.zip | % { Push-AppveyorArtifact $_.FullName -DeploymentName Apps }
  - pwsh: Get-ChildItem -Recurse ./.build/CoverageResults/Coverage.*.cobertura.xml | % { Push-AppveyorArtifact $_.FullName -DeploymentName CoverageReports }

notifications:
- provider: Email
  to:
  - james@thehowats.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
