image: Visual Studio 2017

before_build:
  - ps: nuget restore src

build:
  publish_nuget: true
  project: src/SubEtha.sln

after_build:
  - ps: dotnet publish src/Howatworks.Matrix.Site

test_script:
  - ps: dotnet test src
  
artifacts:
  - path: '**/*.msi'
    name: Installers
    type: file
  - path: '**/Artifacts/*.zip'
    name: ASP.NET Core Apps

notifications:
- provider: Email
  to:
  - james@thehowats.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true