image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: gitversion /l console /output buildserver /ensureassemblyinfo /updateassemblyinfo src/VersionAssemblyInfo.cs
  - ps: nuget restore src

build:
  publish_nuget: true
  project: src/SubEtha.sln

#test:
#  assemblies:
#    only:
#    - '*.Test.dll'
    