image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: nuget restore src
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  publish_nuget: true
  project: src/SubEtha.sln

test:
  assemblies:
    only:
    - '*.Tests.dll'
    