image: Visual Studio 2019

nuget:
  account_feed: true
  
install:
  - ps: dotnet tool restore

build_script:
  - ps: dotnet dotnet-cake

after_build:
  - ps: dotnet publish src/Matrix/Howatworks.Matrix.Site

configuration:
  - Release

test_script:
- ps: dotnet dotnet-cake --target=Test

artifacts:
  - path: src/Thumb.Assistant/Howatworks.Thumb.Assistant.Installer/Artifacts/SubEthaThumbAssistant.msi
    name: Thumb Assistant Installer
    type: file
  - path: src/Thumb.Matrix/Howatworks.Thumb.Matrix.Installer/Artifacts/SubEthaThumbMatrix.msi
    name: Thumb Matrix Installer
    type: file
  - path: src/Matrix/Howatworks.Matrix.Site/Artifacts/Howatworks.Matrix.Site-*.zip
    name: Matrix Site
    type: zip
  - path: src/**/coverage.cobertura.xml
    name: Coverlet Reports
    type: file
  - path: AnalysisResults/Cobertura.xml
    name: ReportGenerator Merged Report
    type: file

notifications:
- provider: Email
  to:
  - james@thehowats.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
