image: Visual Studio 2017

before_build:
  - ps: nuget restore src

build:
  publish_nuget: true
  project: src/SubEtha.sln

test_script:
  - ps: dotnet test src

notifications:
- provider: Email
  to:
  - james@thehowats.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true