image: Visual Studio 2017

before_build:
  - ps: nuget restore src

build:
  publish_nuget: true
  publish_aspnet_core: true
  project: src/SubEtha.sln

test_script:
  - ps: dotnet test src
  
artifacts:
  - path: '**/*.msi'
    name: Installers
    type: file
  - path: 'src/Howatworks.Matrix.Site/**/*.zip'

notifications:
- provider: Email
  to:
  - james@thehowats.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true